# Generated by Django 5.1.3 on 2024-12-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_programmer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=3)),
                ('num_ficha', models.PositiveIntegerField(max_length=7, null=7, unique=True)),
                ('formacion', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
