# Generated by Django 5.1.3 on 2024-12-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='num_ficha',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
